ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        public SelectList Roles;

        private readonly IRoleApplication _roleApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(AccountSearchModel searchModel)
        {
            Roles = new SelectList(_roleApplication.List(), "Id", "Name");
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new RegisterAccount
            {
                Roles = _roleApplication.List()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(RegisterAccount command)
        {
            var result = _accountApplication.Register(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            account.Roles = _roleApplication.List();
            return Partial("Edit", account);
        }

        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword { Id = id };
            return Partial("ChangePassword", command);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        public CreateRole Command;
        private readonly IRoleApplication _roleApplication;

        public CreateModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
        }
        
        public IActionResult OnPost(CreateRole command)
        {
            var result = _roleApplication.Create(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using _0_Framework.Infrastructure;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        public EditRole Command;
        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _roleApplication;
        private readonly IEnumerable<IPermissionExposer> _exposers;

        public EditModel(IRoleApplication roleApplication, IEnumerable<IPermissionExposer> exposers)
        {
            _roleApplication = roleApplication;
            _exposers = exposers;
        }

        public void OnGet(long id)
        {
            Command = _roleApplication.GetDetails(id);
            foreach (var exposer in _exposers)
            {
                var exposedPermissions = exposer.Expose();
                foreach (var (key, value) in exposedPermissions)
                {
                    var group = new SelectListGroup {Name = key};
                    foreach (var permission in value)
                    {
                        var item = new SelectListItem(permission.Name, permission.Code.ToString())
                        {
                            Group = group
                        };

                        if (Command.MappedPermissions.Any(x => x.Code == permission.Code))
                            item.Selected = true;

                        Permissions.Add(item);
                    }
                }
            }
        }

        public IActionResult OnPost(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return RedirectToPage("Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        public List<RoleViewModel> Roles;

        private readonly IRoleApplication _roleApplication;

        public IndexModel(IRoleApplication roleApplication)
        {
            _roleApplication = roleApplication;
        }

        public void OnGet()
        {
            Roles = _roleApplication.List();
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public CreateArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public CreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        public EditArticle Command;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            var result = _articleApplication.Edit(command);
            return RedirectToPage("./Index");
        }
    }
}

ServiceHost/Pages/Account/ChangeAddress.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages.Account
{
    public class ChangeAddressModel : PageModel
    {
        [TempData]
        public string ErrorMessage { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }


        public ChangeAddress Command { get; set; }


        private readonly IAccountApplication _accountApplication;
        private readonly IAuthHelper _authHelper;

        public ChangeAddressModel(IAccountApplication accountApplication, IAuthHelper authHelper)
        {
            _accountApplication = accountApplication;
            _authHelper = authHelper;
        }

        public void OnGet()
        {
            Command = new ChangeAddress() { Id = _authHelper.CurrentAccountInfo().Id, Address = _authHelper.CurrentAccountAddress() };
        }



        public IActionResult OnPostRegister(ChangeAddress command)
        {
            if (ModelState.IsValid)
            {
               
                var result = _accountApplication.ChangeAddress(command);
                if (result.IsSuccedded)
                    SuccessMessage = result.Message;
                else
                    ErrorMessage = result.Message;

                return Page();
            }
            else
            {
                ErrorMessage = "Please fill in the required fields";
                return Page();
            }
        }
    }
}

ServiceHost/Pages/Account/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _0_Framework.Application;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class ChangePasswordModel : PageModel
    {
        [TempData]
        public string ChangePasswordMessage { get; set; }
        [TempData]
        public string ErrorMessage { get; set; }

        public ChangePassword Command { get; set; }

        private readonly IAccountApplication _accountApplication;
        private readonly IAuthHelper _authHelper;

        public ChangePasswordModel(IAccountApplication accountApplication, IAuthHelper authHelper)
        {
            _accountApplication = accountApplication;
            _authHelper = authHelper;
        }

        public void OnGet()
        {
           
        }

        public IActionResult OnPost(ChangePassword command)
        {
            command.Id = _authHelper.CurrentAccountInfo().Id;
            var result = _accountApplication.ChangePassword(command);

            if (result.IsSuccedded)
                ChangePasswordMessage = result.Message;
            else
                ErrorMessage = result.Message;

            return Page();
        }

      


    }
}

ServiceHost/Pages/Account/Login.cshtml.cs
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace ServiceHost.Pages
{
    public class LoginModel : PageModel
    {
        [TempData]
        public string LoginMessage { get; set; }

        public Login Command { get; set; }

        private readonly IAccountApplication _accountApplication;

        public LoginModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin(Login command)
        {
            var result = _accountApplication.Login(command);
            if (result.IsSuccedded)
                return RedirectToPage("/Index");

            LoginMessage = result.Message;
            return Page();
        }

      

       
    }
}

ServiceHost/Pages/Account/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly IAccountApplication _accountApplication;

        public LogoutModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }
        public IActionResult OnGet()
        {
            _accountApplication.Logout();
            return RedirectToPage("/Index");
        }
    }
}

ServiceHost/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class RegisterModel : PageModel
    {

        [TempData]
        public string ErrorMessage { get; set; }

        [TempData]
        public string SuccessMessage { get; set; }


        public RegisterAccount Command { get; set; }


        private readonly IAccountApplication _accountApplication;

        public RegisterModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }



        public IActionResult OnPostRegister(RegisterAccount command)
        {
            if (ModelState.IsValid)
            {
                var result = _accountApplication.Register(command);
                if (result.IsSuccedded)
                    SuccessMessage = result.Message;
                else
                    ErrorMessage = result.Message;

                return Page();
            }
            else
            {
                ErrorMessage = "Please fill in the required fields";
                return Page();
            }
        }
    }
}

ServiceHost/Areas/Administration/Pages/Accounts/Account/ChangePassword.cshtml
@model AccountManagement.Application.Contracts.Account.ChangePassword
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Change Password</h4>
</div>

<form asp-page="./Index" asp-page-handler="ChangePassword"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">Password</label>
                    <input type="password" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="RePassword" class="control-label">Confirm Password</label>
                    <input type="password" class="form-control" asp-for="RePassword">
                    <span asp-validation-for="RePassword" class="error"></span>
                </div>
            </div>
            <input type="hidden" asp-for="Id" value="@Model.Id" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
        </div>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Create.cshtml
@model AccountManagement.Application.Contracts.Account.RegisterAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Create New User</h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">Name</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">User Name</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">Mobile</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Password" class="control-label">Password</label>
                    <input type="text" class="form-control" asp-for="Password">
                    <span asp-validation-for="Password" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="RoleId" class="control-label">Role</label>
                    <select class="form-control" asp-for="RoleId"
                            asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                        <option value="0">Product Category</option>
                    </select>
                    <span asp-validation-for="RoleId" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">Image Profile</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">Create</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Edit.cshtml
@model AccountManagement.Application.Contracts.Account.EditAccount
@{
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">Edit User: @Model.Fullname</h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label">Name</label>
                    <input type="text" class="form-control" asp-for="Fullname">
                    <span asp-validation-for="Fullname" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Username" class="control-label">User Name</label>
                    <input type="text" class="form-control" asp-for="Username">
                    <span asp-validation-for="Username" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label">Mobile</label>
                    <input type="text" class="form-control" asp-for="Mobile">
                    <span asp-validation-for="Mobile" class="error"></span>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="RoleId" class="control-label">Role</label>
                <select class="form-control" asp-for="RoleId"
                        asp-items='new SelectList(Model.Roles, "Id", "Name")'>
                    <option value="0">Product Category</option>
                </select>
                <span asp-validation-for="RoleId" class="error"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Address" class="control-label">Address</label>
                    <input type="text" class="form-control" asp-for="Address">
                    <span asp-validation-for="Address" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProfilePhoto" class="control-label">Image Profile</label>
                    <input type="file" class="form-control" asp-for="ProfilePhoto" accept="image/*">
                    <span asp-validation-for="ProfilePhoto" class="error"></span>
                </div>
            </div>
        </div>
        <input type="hidden" asp-for="Id" value="@Model.Id" />
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">Edit</button>
    </div>
</form>

ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml
@page
@model ServiceHost.Areas.Administration.Pages.Accounts.Account.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "User Management";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">Create New User</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Search In Users</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Fullname"></label>
                        <input class="form-control" asp-for="SearchModel.Fullname" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Username"></label>
                        <input class="form-control" asp-for="SearchModel.Username" placeholder="User Name">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Mobile"></label>
                        <input class="form-control" asp-for="SearchModel.Mobile" placeholder="Mobile">
                    </div>
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.RoleId"></label>
                        <select class="form-control" asp-for="SearchModel.RoleId" asp-items="Model.Roles">
                            <option value="0">Role...</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">Search</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">View All</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Users List (@Model.Accounts.Count)</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>User Name</th>
                                    <th>Mobile</th>
                                    <th>Role</th>
                                    <th>Create Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.Accounts)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.ProfilePhoto" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Fullname</td>
                                        <td>@item.Username</td>
                                        <td>@item.Mobile</td>
                                        <td>@item.Role</td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> Edit
                                            </a>
                                            <a class="btn btn-primary waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "ChangePassword", new { id = item.Id})">
                                                <i class="fa fa-key"></i> Change Password
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}